name: monsterdojo
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.0.0+4
  path: ^1.8.0
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.0
  animated_text_kit: ^4.2.1
  rive: ^0.11.17
  shared_preferences: ^2.0.11
  charts_flutter:
    path: C:\Users\ASUS\Documents\GitHub\charts\charts_flutter
  path_provider: ^2.0.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"  # Ruta a tu ícono principal

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
